# Generated by Django 4.2.6 on 2023-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooker",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
