# Generated by Django 4.2.6 on 2023-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_cooker_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cooker",
            options={"ordering": ["username"]},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
    ]
